name: semantic-release

on: [push]

jobs:
  semantic-release:
    
    runs-on: ubuntu-latest

    container:
      image: node:14.17-alpine

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: apk add git  && cd service && npm ci && cd .. && npm install -D semantic-release-monorepo

    - name: Launch semantic for service
      run: cd service && for moduleName in service logging-index; do cd ../${moduleName} && npx semantic-release -e semantic-release-monorepo --tag-format ${moduleName}-\${version}; done;
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



